# Generated by Django 2.2.11 on 2020-06-27 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('relevant_url', models.URLField(default='Not Provided')),
                ('pub_date', models.DateTimeField(blank=True, null=True)),
                ('short_description', models.TextField(default='Not Provided', max_length=200)),
                ('description', models.TextField(default='Not Provided', max_length=2000)),
                ('teammates', models.IntegerField(default=0)),
                ('vacancy', models.IntegerField(default=1)),
                ('logged_in_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
