# Generated by Django 3.0.8 on 2020-07-12 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20200623_2033'),
        ('team_up', '0004_auto_20200712_1110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teams',
            name='teammates',
        ),
        migrations.AlterField(
            model_name='teams',
            name='logged_in_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Extendeduser'),
        ),
        migrations.CreateModel(
            name='Recruited_Teammates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teammates', models.ManyToManyField(to='team_up.Teams')),
                ('teamup_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Tup_Advertisement', to='team_up.Teams')),
            ],
        ),
    ]
