# Generated by Django 3.0.8 on 2020-07-20 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20200623_2033'),
        ('team_up', '0016_auto_20200718_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logged_in_user', models.CharField(max_length=100)),
                ('requester', models.CharField(max_length=100)),
                ('teamup_advertisement', models.IntegerField()),
                ('status', models.CharField(max_length=2)),
            ],
        ),
        migrations.RenameModel(
            old_name='Recruited_Teammates',
            new_name='RecruitedTeammates',
        ),
        migrations.AlterField(
            model_name='recruitedteammates',
            name='teammates',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teammates', to='accounts.Extendeduser'),
        ),
        migrations.AlterField(
            model_name='teams',
            name='logged_in_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Extendeduser'),
        ),
    ]
