# Generated by Django 3.0.8 on 2020-07-20 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20200623_2033'),
        ('team_up', '0020_auto_20200720_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationstatus',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recruitedteammates',
            name='teammates',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teammates', to='accounts.Extendeduser'),
        ),
        migrations.AlterField(
            model_name='teams',
            name='logged_in_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Extendeduser'),
        ),
    ]
