# Generated by Django 2.2.12 on 2020-06-20 18:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=255)),
                ('last_name', models.CharField(default='', max_length=255)),
                ('gender', models.CharField(blank=True, default='rather_not_say', max_length=255)),
                ('email', models.EmailField(default='', max_length=60, verbose_name='email')),
                ('about_me', models.TextField(default='', max_length=1000)),
                ('portfolio', models.URLField(default='')),
                ('linkedin', models.URLField(default='')),
                ('fackebook', models.URLField(default='')),
                ('twitter', models.URLField(default='')),
                ('other_url', models.URLField(default='')),
                ('dob', models.DateField(null=True, verbose_name='Birthday')),
                ('city', models.CharField(default='', max_length=255)),
                ('country', models.CharField(default='', max_length=255)),
                ('phone', models.IntegerField(default=0)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date_joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last_login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
