# Generated by Django 3.0.8 on 2020-07-21 19:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extendeduser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(default='', max_length=255)),
                ('gender', models.CharField(blank=True, default='rather_not_say', max_length=255)),
                ('email', models.EmailField(default='', max_length=60, verbose_name='email')),
                ('about_me', models.TextField(default="Let's Team-up!", max_length=1000)),
                ('portfolio', models.URLField(default='Not Provided')),
                ('linkedin', models.URLField(default='Not Provided')),
                ('facebook', models.URLField(default='Not Provided')),
                ('twitter', models.URLField(default='Not Provided')),
                ('other_url', models.URLField(default='Not Provided')),
                ('city', models.CharField(default='', max_length=255)),
                ('country', models.CharField(default='', max_length=255)),
                ('phone', models.CharField(default='0000000000', max_length=17)),
                ('date_joined', models.DateTimeField(auto_now=True, verbose_name='date_joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last_login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
        ),
    ]
