# Generated by Django 2.2.12 on 2020-06-20 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200620_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='about_me',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='extendeduser',
            name='city',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='extendeduser',
            name='country',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='extendeduser',
            name='date_joined',
            field=models.DateTimeField(auto_now=True, verbose_name='date_joined'),
        ),
        migrations.AddField(
            model_name='extendeduser',
            name='dob',
            field=models.DateField(null=True, verbose_name='Birthday'),
        ),
        migrations.AddField(
            model_name='extendeduser',
            name='email',
            field=models.EmailField(default='', max_length=60, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='extendeduser',
            name='fackebook',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='extendeduser',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='extendeduser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='extendeduser',
            name='last_login',
            field=models.DateTimeField(auto_now=True, verbose_name='last_login'),
        ),
        migrations.AddField(
            model_name='extendeduser',
            name='linkedin',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='extendeduser',
            name='other_url',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='extendeduser',
            name='phone',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='extendeduser',
            name='portfolio',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='extendeduser',
            name='twitter',
            field=models.URLField(default=''),
        ),
    ]
