# Generated by Django 2.2.12 on 2020-06-21 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200620_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='about_me',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='city',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='country',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='email',
            field=models.EmailField(max_length=60, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='fackebook',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='first_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='last_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='linkedin',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='other_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='portfolio',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='twitter',
            field=models.URLField(),
        ),
    ]
