# Generated by Django 2.2.12 on 2020-06-21 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200621_1813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extendeduser',
            name='dob',
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='about_me',
            field=models.TextField(default="Let's Team-up!", max_length=1000),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='city',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='country',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='email',
            field=models.EmailField(default='', max_length=60, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='fackebook',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='last_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='linkedin',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='other_url',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='portfolio',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='twitter',
            field=models.URLField(default=''),
        ),
    ]
