# Generated by Django 2.2.12 on 2020-06-21 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200621_1910'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extendeduser',
            old_name='fackebook',
            new_name='facebook',
        ),
    ]
