# Generated by Django 2.2.11 on 2020-06-23 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200621_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='facebook',
            field=models.URLField(default='Not Provided'),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='linkedin',
            field=models.URLField(default='Not Provided'),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='other_url',
            field=models.URLField(default='Not Provided'),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='portfolio',
            field=models.URLField(default='Not Provided'),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='twitter',
            field=models.URLField(default='Not Provided'),
        ),
    ]
