# Generated by Django 2.2.11 on 2020-06-23 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200623_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='phone',
            field=models.CharField(default='0000000000', max_length=17),
        ),
    ]
